# Generated by Django 4.2.23 on 2025-07-02 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('party_a_signature', models.CharField(blank=True, max_length=255, null=True)),
                ('party_b_signature', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SIGNED', 'Signed'), ('UNDER_REVIEW', 'Under Review'), ('REVIEWED', 'Reviewed')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lawyer_review_comments', models.TextField(blank=True, null=True)),
                ('file_export', models.FileField(blank=True, null=True, upload_to='contracts/')),
                ('lawyer_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_contracts', to=settings.AUTH_USER_MODEL)),
                ('party_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts_as_party_a', to=settings.AUTH_USER_MODEL)),
                ('party_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts_as_party_b', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
