# Generated by Django 4.2.23 on 2025-07-02 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_alter_contract_options_remove_contract_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='text_version',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='signature',
            name='barcode_svg',
            field=models.TextField(blank=True),
        ),
    ]
