# Generated by Django 4.2.23 on 2025-07-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_contract_text_version_signature_barcode_svg'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SIGNED_BY_CLIENT', 'Signed by Client'), ('SIGNED_BY_LAWYER', 'Signed by Lawyer'), ('COMPLETED', 'Completed'), ('EXPORTED', 'Exported')], default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
