# Generated by Django 4.2.23 on 2025-07-17 15:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_contract_status_review_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='public_key',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signature',
            name='signature_hash',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
